apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ky38e5ksh-python 
  janus-idp.io/tekton: ky38e5ksh-python
  backstage.io/kubernetes-id: ky38e5ksh-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ky38e5ksh-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml