apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ky38e5ksh-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ky38e5ksh-python 
  name: ky38e5ksh-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ky38e5ksh-python 
